name: publish-build
on:
  release:
    types: [released]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Install project dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Create ZIP folder
        uses: thedoctor0/zip-release@master
        with:
          filename: 'build.zip'
          directory: 'build'
      - name: Upload build to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/build.zip
          tag: ${{ github.ref }}
